CREATE SCHEMA IF NOT EXISTS HIBERNATE_REPOSITORY;
SET SCHEMA HIBERNATE_REPOSITORY;
CREATE TABLE IF NOT EXISTS Person
(
    ID   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    AGE  int     NOT NULL
);

CREATE TABLE IF NOT EXISTS Item
(
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PERSON_ID INT ,
    ITEM_NAME VARCHAR(100) NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(id) ON DELETE SET NULL
);

MERGE INTO PERSON (NAME, AGE)  KEY (NAME, AGE) VALUES ( 'Sergey', 34),
                                     ( 'Ilmira', 35),
                                     ( 'Dmitry', 10),
                                     ( 'Alice', 5),
                                     ( 'Milana', 2);

MERGE INTO ITEM (PERSON_ID, ITEM_NAME) KEY (PERSON_ID, ITEM_NAME) VALUES ( 1, 'Realme GT Neo 5' ),
                                              ( 1, 'Lenovo Thinkpad' ),
                                              ( 2, 'Iphone 11' ),
                                              ( 2, 'Lenovo Legion' ),
                                              ( 3, 'Hotwheels Monster truck' ),
                                              ( 4, 'Lol doll' ),
                                              ( 5, 'Book' );